### ISSUE TITLE
MacOS showing me an error when press [Command + Shift + V] and not show the Clipboard logs

### ISSUE THREAD

**Issue by Y0usefmahdi** [aklein13/cp-clip#20]
MacOS Monterey (12.4)
MacBook Pro (16-inch, 2021)
Chip: Apple M1 Pro

====
Error Screen 
====

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<Object>
at BrowserWindow.setBounds (electron/js2c/browser_init.js:524:21)
at Function.$ (/Applications/cp-clip.app/Contents/Resources/app.asar/webpack:/app/main.prod.js:300:21)

**Comment by aklein13** [comment]
@Y0usefmahdi Does the same thing happen if you try to open Cleanup window?

I guess it might be caused by M1 because it works on 3 Macs (1 x Monterey, 2 x Catalina) I have access to but all of them are Intel based.

I can try building M1 specific version but I cannot really test if it works. Would you be able to test it for me?

**Comment by Y0usefmahdi** [comment]
nope, the Cleanup windows works
Yes of course please can you send me a build with M1?

@aklein13

**Comment by aklein13** [comment]
@Y0usefmahdi It wasn't related to M1 after all and I published a version with a fix https://github.com/aklein13/cp-clip/releases/tag/v0.6.0 so it should work now. I also created a macOS guide to setup cp-clip as it's a bit more complicated then on Windows because of system permissions: https://github.com/aklein13/cp-clip/blob/master/docs/macOS.md . Feel free to create a new issue if something doesn't work.

Regarding M1 version I get some errors when compiling. Not sure if it's because of dependecies I use or the fact that I use Intel mac. Anyway I will try to look into that in the future to improve performance on M1.

**Comment by Y0usefmahdi** [comment]
Great, it works like charm now, thank you for your efforts @aklein13
Yes please, if you can compile it for M1 will be great because it will take less CPU usage than the Intel build...

<br /> 

There is something I noticed when i restart the mac, the cp-clip icon stay on the dock until i click "Command-shift-v" it will disappear, can you make it not show by default without anything being done by me?
preview: https://imgur.com/9iTyu1W

<br /> 

The last thing, I asked you **before 5 month** If you can improve the design and add new features, such as those in the famous Paste app (https://pasteapp.io/), but since then you have not made any new additions to the program, do you have any intention of doing so?

Features like (from Paste):
- Nice UI
- Drag & Drop links & file (Maybe this electron app can help you do the job https://github.com/GameGodS3/DropPoint)
- ORGANIZE and Pin important links and paste with colors or categories (It will save a lot of time)
- Search and see where you copied the paste from (which app)

If you have any intention to do or add the features above, tell me or attach your email below and I will help you and design a beautiful UI for your program and send you the design so you can code it...

<br /> 
Thank you for your efforts in releasing this powerful update
You are a creative person, keep it up my friend

**Comment by aklein13** [comment]
Thank you for your feedback @Y0usefmahdi

I'll start with the dock icon you noticed. Sure, I'll get rid of it in the next release, probably this week.

Regarding M1 version I managed to build it but a few things broke because of electron version upgrade I needed to do. I'll need to fix these bugs first, not sure how long it'll take. Electron version upgrade is always a pain but it's required for M1.


Now regarding the features you listed from Paste, first of all I want to say that cp-clip is currently mostly in maintenance mode. That means I will try to fix errors and I can make some quick changes but I will not add new features for now. This might change in the future but not anytime soon as I'm quite busy :/ Exception for this will M1 support as I already started it and I will need it at some point anyway.

Now for the features you listed:
1. I agree that cp-clip is a big ugly but on the other hand I don't really like Paste interface. It shows less information and feels like it takes more space at the same time. Because of that I prefer to keep current cp-clip interface.

2. I don't really want to include drag and drop box from DropPoint but I could add a support for files. Right now if you copy file/files/directory it will end up as string in cp-clip and you will not be able to paste it using cp-clip. I can make it work and I think it would be useful.

3. That's a big feature. While I think it would be useful I can't commit to it right now. One way I can see it being done is tabs on top of current clipboard window. By the way cp-clip currently has a poor version useful for pinning important stuff. To use it you need to open the clipboard window, select an entry with arrow keys and press (Command (Mac)/Control(Win) + Alt + [any number from 1 to 9]. This will save selected entry and you can now paste it directly into any application using the same key combination without opening cp-cli main window. You can also preview current saved entries: https://i.imgur.com/AaTMvDB.png . I know this is way more limited then DropPoint but I find it pretty useful.

4. This will not be possible in current method of getting clipboard value. I'm using native electron implementation and it doesn't return the application name.

**Comment by aklein13** [comment]
@Y0usefmahdi Would you mind to try the new M1 build? https://github.com/aklein13/cp-clip/releases/tag/v0.6.2

cp-clip-0.6.2-arm64.dmg is the file, no idea if it works but I hope so :D

**Comment by Y0usefmahdi** [comment]
nope, It doesn't launch at all, and show this error: @aklein13 

====

Uncaught Exception:
Error: dlopen(/var/folders/bl/_nn2r0dx6h59twswy46r6h940000gn/T/.org.aklein13.cp-clip.6KWHeq, 0x0001): tried: '/var/folders/bl/_nn2r0dx6h59twswy46r6h940000gn/T/.org.aklein13.cp-clip.6KWHeq' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/private/var/folders/bl/_nn2r0dx6h59twswy46r6h940000gn/T/.org.aklein13.cp-clip.6KWHeq' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/Applications/cp-clip.app/Contents/Resources/app.asar/node_modules/robotjs/index.js:1:15)
at Module._compile (internal/modules/cjs/loader.js:1078:30)

**Comment by aklein13** [comment]
Thanks, I'll try to investigate this
